package com.kevo.LeavesRemaster.enums;

public enum Permissions {
    VIEW_OWN_LEAVES,
    MANAGE_OWN_LEAVES,
    VIEW_OTHER_LEAVES,
    MANAGE_OTHER_LEAVES,
    VIEW_LEAVE_TYPE,
    MANAGE_LEAVE_TYPE,
    VIEW_LEAVE_POLICY,
    MANAGE_LEAVE_POLICY,
    MANAGE_HOLIDAYS,
    VIEW_MANAGER_DASHBOARD,
    MANAGE_MANAGER_DASHBOARD,
    VIEW_HR_DASHBOARD,
    MANAGE_HR_DASHBOARD,
    VIEW_LEAVE_APPROVER,
    MANAGE_LEAVE_APPROVER
}
